// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRefreshSession = `-- name: CreateRefreshSession :exec
INSERT INTO refresh_sessions (user_id, token_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshSessionParams struct {
	UserID    int64              `db:"user_id" json:"user_id"`
	TokenID   string             `db:"token_id" json:"token_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, CreateRefreshSession,
		arg.UserID,
		arg.TokenID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const CreateUser = `-- name: CreateUser :one
WITH inserted AS (
    INSERT INTO users (role_id, email, password_hash)
    SELECT id, $1, $2
    FROM roles
    WHERE roles.name = $3
    RETURNING id, role_id, email, password_hash, is_active, created_at, updated_at, deleted_at
)
SELECT inserted.id, inserted.email, inserted.password_hash, roles.name AS role_name,
       inserted.is_active, inserted.created_at, inserted.updated_at, inserted.deleted_at
FROM inserted
JOIN roles ON roles.id = inserted.role_id
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	RoleName     string `db:"role_name" json:"role_name"`
}

type CreateUserRow struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	RoleName     string             `db:"role_name" json:"role_name"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Email, arg.PasswordHash, arg.RoleName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const GetRefreshSessionByTokenID = `-- name: GetRefreshSessionByTokenID :one
SELECT id, user_id, token_id, token_hash, expires_at, revoked_at, replaced_by_token_id, created_at
FROM refresh_sessions
WHERE token_id = $1
`

func (q *Queries) GetRefreshSessionByTokenID(ctx context.Context, tokenID string) (*RefreshSession, error) {
	row := q.db.QueryRow(ctx, GetRefreshSessionByTokenID, tokenID)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
	)
	return &i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id, users.email, users.password_hash, roles.name AS role_name,
       users.is_active, users.created_at, users.updated_at, users.deleted_at
FROM users
JOIN roles ON roles.id = users.role_id
WHERE LOWER(users.email) = LOWER($1) AND users.deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	RoleName     string             `db:"role_name" json:"role_name"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT users.id, users.email, users.password_hash, roles.name AS role_name,
       users.is_active, users.created_at, users.updated_at, users.deleted_at
FROM users
JOIN roles ON roles.id = users.role_id
WHERE users.id = $1 AND users.deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	RoleName     string             `db:"role_name" json:"role_name"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const RevokeRefreshSession = `-- name: RevokeRefreshSession :execrows
UPDATE refresh_sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE token_id = $1
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenID string) (int64, error) {
	result, err := q.db.Exec(ctx, RevokeRefreshSession, tokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const RotateRefreshSession = `-- name: RotateRefreshSession :execrows
UPDATE refresh_sessions
SET revoked_at = NOW(), replaced_by_token_id = $1
WHERE token_id = $2 AND revoked_at IS NULL AND expires_at > NOW()
`

type RotateRefreshSessionParams struct {
	ReplacedByTokenID *string `db:"replaced_by_token_id" json:"replaced_by_token_id"`
	TokenID           string  `db:"token_id" json:"token_id"`
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, RotateRefreshSession, arg.ReplacedByTokenID, arg.TokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
