// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
)

const ClaimDocumentProcessing = `-- name: ClaimDocumentProcessing :execrows
UPDATE documents SET status = 'processing', processing_error = NULL, updated_at = NOW()
WHERE id = $1 AND status IN ('pending', 'failed') AND deleted_at IS NULL
`

func (q *Queries) ClaimDocumentProcessing(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, ClaimDocumentProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const CountAllDocuments = `-- name: CountAllDocuments :one
SELECT COUNT(*) FROM documents WHERE deleted_at IS NULL
`

func (q *Queries) CountAllDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountAllDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountDocumentsByOwner = `-- name: CountDocumentsByOwner :one
SELECT COUNT(*) FROM documents WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountDocumentsByOwner(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountDocumentsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateDocument = `-- name: CreateDocument :one
INSERT INTO documents (owner_id, original_name, media_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, original_name, media_type, size_bytes, storage_key, checksum_sha256, status, processing_error, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	OwnerID      int64  `db:"owner_id" json:"owner_id"`
	OriginalName string `db:"original_name" json:"original_name"`
	MediaType    string `db:"media_type" json:"media_type"`
	SizeBytes    int64  `db:"size_bytes" json:"size_bytes"`
	StorageKey   string `db:"storage_key" json:"storage_key"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (*Document, error) {
	row := q.db.QueryRow(ctx, CreateDocument,
		arg.OwnerID,
		arg.OriginalName,
		arg.MediaType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OriginalName,
		&i.MediaType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.ProcessingError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const GetDocumentByID = `-- name: GetDocumentByID :one
SELECT id, owner_id, original_name, media_type, size_bytes, storage_key, checksum_sha256, status, processing_error, created_at, updated_at, deleted_at FROM documents WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByID(ctx context.Context, id int64) (*Document, error) {
	row := q.db.QueryRow(ctx, GetDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OriginalName,
		&i.MediaType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.ProcessingError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const ListAllDocuments = `-- name: ListAllDocuments :many
SELECT id, owner_id, original_name, media_type, size_bytes, storage_key, checksum_sha256, status, processing_error, created_at, updated_at, deleted_at FROM documents
WHERE deleted_at IS NULL
ORDER BY id DESC LIMIT $2 OFFSET $1
`

type ListAllDocumentsParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]*Document, error) {
	rows, err := q.db.Query(ctx, ListAllDocuments, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OriginalName,
			&i.MediaType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.ChecksumSha256,
			&i.Status,
			&i.ProcessingError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_id, original_name, media_type, size_bytes, storage_key, checksum_sha256, status, processing_error, created_at, updated_at, deleted_at FROM documents
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListDocumentsByOwnerParams struct {
	OwnerID    int64 `db:"owner_id" json:"owner_id"`
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListDocumentsByOwner(ctx context.Context, arg ListDocumentsByOwnerParams) ([]*Document, error) {
	rows, err := q.db.Query(ctx, ListDocumentsByOwner, arg.OwnerID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OriginalName,
			&i.MediaType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.ChecksumSha256,
			&i.Status,
			&i.ProcessingError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkDocumentFailed = `-- name: MarkDocumentFailed :execrows
UPDATE documents SET status = 'failed', processing_error = $1, updated_at = NOW()
WHERE id = $2 AND status = 'processing' AND deleted_at IS NULL
`

type MarkDocumentFailedParams struct {
	ProcessingError *string `db:"processing_error" json:"processing_error"`
	ID              int64   `db:"id" json:"id"`
}

func (q *Queries) MarkDocumentFailed(ctx context.Context, arg MarkDocumentFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkDocumentFailed, arg.ProcessingError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const MarkDocumentReady = `-- name: MarkDocumentReady :execrows
UPDATE documents
SET status = 'ready', checksum_sha256 = $1, size_bytes = $2, processing_error = NULL, updated_at = NOW()
WHERE id = $3 AND status = 'processing' AND deleted_at IS NULL
`

type MarkDocumentReadyParams struct {
	ChecksumSha256 *string `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64   `db:"size_bytes" json:"size_bytes"`
	ID             int64   `db:"id" json:"id"`
}

func (q *Queries) MarkDocumentReady(ctx context.Context, arg MarkDocumentReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkDocumentReady, arg.ChecksumSha256, arg.SizeBytes, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SoftDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents SET deleted_at = COALESCE(deleted_at, NOW()), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteDocument(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, SoftDeleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
