// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID              int64              `db:"id" json:"id"`
	OwnerID         int64              `db:"owner_id" json:"owner_id"`
	OriginalName    string             `db:"original_name" json:"original_name"`
	MediaType       string             `db:"media_type" json:"media_type"`
	SizeBytes       int64              `db:"size_bytes" json:"size_bytes"`
	StorageKey      string             `db:"storage_key" json:"storage_key"`
	ChecksumSha256  *string            `db:"checksum_sha256" json:"checksum_sha256"`
	Status          string             `db:"status" json:"status"`
	ProcessingError *string            `db:"processing_error" json:"processing_error"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type RefreshSession struct {
	ID                int64              `db:"id" json:"id"`
	UserID            int64              `db:"user_id" json:"user_id"`
	TokenID           string             `db:"token_id" json:"token_id"`
	TokenHash         string             `db:"token_hash" json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ReplacedByTokenID *string            `db:"replaced_by_token_id" json:"replaced_by_token_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Role struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	RoleID       int64              `db:"role_id" json:"role_id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
