// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ClaimDocumentProcessing(ctx context.Context, id int64) (int64, error)
	CountAllDocuments(ctx context.Context) (int64, error)
	CountDocumentsByOwner(ctx context.Context, ownerID int64) (int64, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (*Document, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	GetDocumentByID(ctx context.Context, id int64) (*Document, error)
	GetRefreshSessionByTokenID(ctx context.Context, tokenID string) (*RefreshSession, error)
	GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error)
	ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]*Document, error)
	ListDocumentsByOwner(ctx context.Context, arg ListDocumentsByOwnerParams) ([]*Document, error)
	MarkDocumentFailed(ctx context.Context, arg MarkDocumentFailedParams) (int64, error)
	MarkDocumentReady(ctx context.Context, arg MarkDocumentReadyParams) (int64, error)
	RevokeRefreshSession(ctx context.Context, tokenID string) (int64, error)
	RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (int64, error)
	SoftDeleteDocument(ctx context.Context, id int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
